"""create estimate tables

Revision ID: 0f9cdf07995f
Revises: 
Create Date: 2026-01-21 16:12:40.632927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9cdf07995f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimate_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('reference_url', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimate_requests_email'), 'estimate_requests', ['email'], unique=False)
    op.create_index(op.f('ix_estimate_requests_id'), 'estimate_requests', ['id'], unique=False)
    op.create_table('estimate_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('site_type', sa.String(length=50), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('md_count', sa.Float(), nullable=True),
    sa.Column('estimated_cost_min', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_max', sa.Integer(), nullable=True),
    sa.Column('estimated_days', sa.Integer(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('scope_included', sa.Text(), nullable=True),
    sa.Column('scope_excluded', sa.Text(), nullable=True),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['estimate_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimate_responses_id'), 'estimate_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estimate_responses_id'), table_name='estimate_responses')
    op.drop_table('estimate_responses')
    op.drop_index(op.f('ix_estimate_requests_id'), table_name='estimate_requests')
    op.drop_index(op.f('ix_estimate_requests_email'), table_name='estimate_requests')
    op.drop_table('estimate_requests')
    # ### end Alembic commands ###
